# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import detector_pb2 as detector__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in detector_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DetectorServiceStub(object):
    """AI Worker service — Python side handles ML inference
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectObjects = channel.unary_unary(
                '/orbital_eye.DetectorService/DetectObjects',
                request_serializer=detector__pb2.DetectRequest.SerializeToString,
                response_deserializer=detector__pb2.DetectResponse.FromString,
                _registered_method=True)
        self.ClassifyObject = channel.unary_unary(
                '/orbital_eye.DetectorService/ClassifyObject',
                request_serializer=detector__pb2.ClassifyRequest.SerializeToString,
                response_deserializer=detector__pb2.ClassifyResponse.FromString,
                _registered_method=True)
        self.DetectChanges = channel.unary_unary(
                '/orbital_eye.DetectorService/DetectChanges',
                request_serializer=detector__pb2.ChangeRequest.SerializeToString,
                response_deserializer=detector__pb2.ChangeResponse.FromString,
                _registered_method=True)
        self.Enhance = channel.unary_unary(
                '/orbital_eye.DetectorService/Enhance',
                request_serializer=detector__pb2.EnhanceRequest.SerializeToString,
                response_deserializer=detector__pb2.EnhanceResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/orbital_eye.DetectorService/Health',
                request_serializer=detector__pb2.HealthRequest.SerializeToString,
                response_deserializer=detector__pb2.HealthResponse.FromString,
                _registered_method=True)


class DetectorServiceServicer(object):
    """AI Worker service — Python side handles ML inference
    """

    def DetectObjects(self, request, context):
        """Detect objects in a satellite image tile
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyObject(self, request, context):
        """Classify a detected object
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectChanges(self, request, context):
        """Compare two images for changes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Enhance(self, request, context):
        """Super-resolution enhancement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DetectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectObjects,
                    request_deserializer=detector__pb2.DetectRequest.FromString,
                    response_serializer=detector__pb2.DetectResponse.SerializeToString,
            ),
            'ClassifyObject': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyObject,
                    request_deserializer=detector__pb2.ClassifyRequest.FromString,
                    response_serializer=detector__pb2.ClassifyResponse.SerializeToString,
            ),
            'DetectChanges': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectChanges,
                    request_deserializer=detector__pb2.ChangeRequest.FromString,
                    response_serializer=detector__pb2.ChangeResponse.SerializeToString,
            ),
            'Enhance': grpc.unary_unary_rpc_method_handler(
                    servicer.Enhance,
                    request_deserializer=detector__pb2.EnhanceRequest.FromString,
                    response_serializer=detector__pb2.EnhanceResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=detector__pb2.HealthRequest.FromString,
                    response_serializer=detector__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orbital_eye.DetectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orbital_eye.DetectorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DetectorService(object):
    """AI Worker service — Python side handles ML inference
    """

    @staticmethod
    def DetectObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orbital_eye.DetectorService/DetectObjects',
            detector__pb2.DetectRequest.SerializeToString,
            detector__pb2.DetectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orbital_eye.DetectorService/ClassifyObject',
            detector__pb2.ClassifyRequest.SerializeToString,
            detector__pb2.ClassifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectChanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orbital_eye.DetectorService/DetectChanges',
            detector__pb2.ChangeRequest.SerializeToString,
            detector__pb2.ChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Enhance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orbital_eye.DetectorService/Enhance',
            detector__pb2.EnhanceRequest.SerializeToString,
            detector__pb2.EnhanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orbital_eye.DetectorService/Health',
            detector__pb2.HealthRequest.SerializeToString,
            detector__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
