// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: proto/detector.proto

package gen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DetectorService_DetectObjects_FullMethodName  = "/orbital_eye.DetectorService/DetectObjects"
	DetectorService_ClassifyObject_FullMethodName = "/orbital_eye.DetectorService/ClassifyObject"
	DetectorService_DetectChanges_FullMethodName  = "/orbital_eye.DetectorService/DetectChanges"
	DetectorService_Enhance_FullMethodName        = "/orbital_eye.DetectorService/Enhance"
	DetectorService_Health_FullMethodName         = "/orbital_eye.DetectorService/Health"
)

// DetectorServiceClient is the client API for DetectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AI Worker service — Python side handles ML inference
type DetectorServiceClient interface {
	// Detect objects in a satellite image tile
	DetectObjects(ctx context.Context, in *DetectRequest, opts ...grpc.CallOption) (*DetectResponse, error)
	// Classify a detected object
	ClassifyObject(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*ClassifyResponse, error)
	// Compare two images for changes
	DetectChanges(ctx context.Context, in *ChangeRequest, opts ...grpc.CallOption) (*ChangeResponse, error)
	// Super-resolution enhancement
	Enhance(ctx context.Context, in *EnhanceRequest, opts ...grpc.CallOption) (*EnhanceResponse, error)
	// Health check
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type detectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDetectorServiceClient(cc grpc.ClientConnInterface) DetectorServiceClient {
	return &detectorServiceClient{cc}
}

func (c *detectorServiceClient) DetectObjects(ctx context.Context, in *DetectRequest, opts ...grpc.CallOption) (*DetectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectResponse)
	err := c.cc.Invoke(ctx, DetectorService_DetectObjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *detectorServiceClient) ClassifyObject(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*ClassifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassifyResponse)
	err := c.cc.Invoke(ctx, DetectorService_ClassifyObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *detectorServiceClient) DetectChanges(ctx context.Context, in *ChangeRequest, opts ...grpc.CallOption) (*ChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeResponse)
	err := c.cc.Invoke(ctx, DetectorService_DetectChanges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *detectorServiceClient) Enhance(ctx context.Context, in *EnhanceRequest, opts ...grpc.CallOption) (*EnhanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnhanceResponse)
	err := c.cc.Invoke(ctx, DetectorService_Enhance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *detectorServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, DetectorService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DetectorServiceServer is the server API for DetectorService service.
// All implementations must embed UnimplementedDetectorServiceServer
// for forward compatibility.
//
// AI Worker service — Python side handles ML inference
type DetectorServiceServer interface {
	// Detect objects in a satellite image tile
	DetectObjects(context.Context, *DetectRequest) (*DetectResponse, error)
	// Classify a detected object
	ClassifyObject(context.Context, *ClassifyRequest) (*ClassifyResponse, error)
	// Compare two images for changes
	DetectChanges(context.Context, *ChangeRequest) (*ChangeResponse, error)
	// Super-resolution enhancement
	Enhance(context.Context, *EnhanceRequest) (*EnhanceResponse, error)
	// Health check
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedDetectorServiceServer()
}

// UnimplementedDetectorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDetectorServiceServer struct{}

func (UnimplementedDetectorServiceServer) DetectObjects(context.Context, *DetectRequest) (*DetectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectObjects not implemented")
}
func (UnimplementedDetectorServiceServer) ClassifyObject(context.Context, *ClassifyRequest) (*ClassifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClassifyObject not implemented")
}
func (UnimplementedDetectorServiceServer) DetectChanges(context.Context, *ChangeRequest) (*ChangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectChanges not implemented")
}
func (UnimplementedDetectorServiceServer) Enhance(context.Context, *EnhanceRequest) (*EnhanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enhance not implemented")
}
func (UnimplementedDetectorServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedDetectorServiceServer) mustEmbedUnimplementedDetectorServiceServer() {}
func (UnimplementedDetectorServiceServer) testEmbeddedByValue()                         {}

// UnsafeDetectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DetectorServiceServer will
// result in compilation errors.
type UnsafeDetectorServiceServer interface {
	mustEmbedUnimplementedDetectorServiceServer()
}

func RegisterDetectorServiceServer(s grpc.ServiceRegistrar, srv DetectorServiceServer) {
	// If the following call panics, it indicates UnimplementedDetectorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DetectorService_ServiceDesc, srv)
}

func _DetectorService_DetectObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectorServiceServer).DetectObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectorService_DetectObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectorServiceServer).DetectObjects(ctx, req.(*DetectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DetectorService_ClassifyObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectorServiceServer).ClassifyObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectorService_ClassifyObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectorServiceServer).ClassifyObject(ctx, req.(*ClassifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DetectorService_DetectChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectorServiceServer).DetectChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectorService_DetectChanges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectorServiceServer).DetectChanges(ctx, req.(*ChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DetectorService_Enhance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnhanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectorServiceServer).Enhance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectorService_Enhance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectorServiceServer).Enhance(ctx, req.(*EnhanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DetectorService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectorServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectorService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectorServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DetectorService_ServiceDesc is the grpc.ServiceDesc for DetectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DetectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orbital_eye.DetectorService",
	HandlerType: (*DetectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DetectObjects",
			Handler:    _DetectorService_DetectObjects_Handler,
		},
		{
			MethodName: "ClassifyObject",
			Handler:    _DetectorService_ClassifyObject_Handler,
		},
		{
			MethodName: "DetectChanges",
			Handler:    _DetectorService_DetectChanges_Handler,
		},
		{
			MethodName: "Enhance",
			Handler:    _DetectorService_Enhance_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _DetectorService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/detector.proto",
}
